# Generated by Django 3.1.1 on 2020-09-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('cuntry', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('emp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adr', to='onetoone.employee')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
