# Generated by Django 3.1.1 on 2020-09-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adr', to='onetoone.employee'),
        ),
    ]
