# Generated by Django 3.1.1 on 2020-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0002_auto_20200909_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='emp',
        ),
        migrations.AddField(
            model_name='address',
            name='emp',
            field=models.ManyToManyField(null=True, related_name='adr', to='onetoone.Employee'),
        ),
    ]
